### ISSUE TITLE
Please add a licence to Go Incognito and "channel-content"

### ISSUE THREAD

**Issue by ghost** [techlore/go-incognito#19]
It looks like Go Incognito doesn't have a licence set, so that would mean all rights reserved and a bit confusing on what we can do with Go Incognito and what we can not. It doesn't seem to have much legal power in the recent years but afaik you can not share media licenced under this but it has a torrent? `channel-content` doesnt seem to have a licence as well. A licence to clear this confusion would be nice. Thanks.

**Comment by techlore-official** [comment]
The readme for Go Incognito is pretty thorough on this. 

- The very top of the readme shows the CC license (http://creativecommons.org/licenses/by-nc-nd/4.0/) 
- The bottom breaks down what you can do with all the videos (https://github.com/techlore/go-incognito#contributing-to-go-incognito)

The only reason GI is not directly assigned a license on GitHub is because there are two variants, and I don't want there to be confusion between free & premium, which the current readme outlines are two different things.

For channel-content, I just went ahead and added a CC0 license to the repo! (https://github.com/techlore/channel-content/commit/5baa966462ac005248bf882f886bccac85f0be5f)

Channel content
